version: '3.8'

services:
  trendconnect:
    image: ${DOCKER_USERNAME}/trendconnect:latest
    container_name: trendconnect
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./content_database:/app/content_database
    environment:
      - PYTHONPATH=/app
      - PORT=8000
      - HOST=0.0.0.0
      - ENVIRONMENT=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - trendconnect-net

networks:
  trendconnect-net:
    driver: bridge